type Address {
  lineone: String!
  linetwo: String
  city: String!
  state: StateCode
  zipcode: String
}

enum StateCode {
  MO
  KS
}

type User {
  id: ID!
  email: String!
  firstname: String
  lastname: String
  address: Address
}

type Query {
  getUser(email: String!): User
}
